# Generated by Django 5.2.4 on 2025-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_jp', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='Answer')),
                ('answer_jp', models.TextField(null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
            },
        ),
    ]
