# Generated by Django 5.2.4 on 2025-08-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question_jp',
            new_name='question_ja',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_jp',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ja',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
    ]
