# Generated by Django 5.2.4 on 2025-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Video URL')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ja', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_files/', verbose_name='Video File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Video ',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
        ),
    ]
