version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    container_name: japan_django_app
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - envs/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - japan_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - envs/.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - japan_network

  japan_bot:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    image: japan_bot
    command: python bot/app.py
    volumes:
      - .:/app
    env_file:
      - envs/.env
    restart: always
    networks:
      - japan_network

networks:
  japan_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  mysql_data: