# Generated by Django 5.2.4 on 2025-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_jp', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_jp', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('price_ru', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Price')),
                ('price_jp', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Price')),
                ('price_en', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Product ',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
