# Generated by Django 5.2.4 on 2025-08-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_jp',
            new_name='description_ja',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_jp',
            new_name='title_ja',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_jp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ru',
        ),
    ]
